name: Deploy to Dev Server

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (optional if not using local repo)
        uses: actions/checkout@v3

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.221.19.69
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          script: |
            export PATH=$PATH:/home/ubuntu/.local/share/pnpm:/home/ubuntu/.nvm/versions/node/v22.17.1/bin
            cd devops-ci-cd/
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
